name=Wiimote
version=1.0.0
author=takeru
maintainer=takeru
sentence=Wiimote Bluetooth library for ESP32
paragraph=Connect and receive data from Wiimote controllers
category=Communication
url=https://github.com/takeru/Wiimote
architectures=esp32
